### ISSUE TITLE
cmdlist/../libpBat.h:31:10: fatal error: ../config.h: No such file or directory

### ISSUE THREAD

**Issue by pandasoli** [darkbatcher/picobat#1]
![image](https://user-images.githubusercontent.com/76575902/190879739-3f50064b-635c-4895-84d4-6246a4b65472.png)

I downloaded all the files from the current version

**Comment by TSnake41** [comment]
You need to do `make config` first.

**Comment by TheKvc** [comment]
i think, this is resloved. (http://picobat.org/download.html)

or is there any other reason, that this is still open?

**Comment by TSnake41** [comment]
> i think, this is resloved. (http://picobat.org/download.html)
> 
> or is there any other reason, that this is still open?

Just in case the author answered, but it was not the case for ages, so let's close it.
