### ISSUE TITLE
Can we create custom subfunc?

### ISSUE THREAD

**Issue by GroophyLifefor** [darkbatcher/picobat#2]
It is possible EnableDelayedExpansion for substring.
like: ` %var:~10,5%`

But if we can make our custom subfuncs like
```
  SET EnableDelayedExpansion
  SET Var=HeLLO
  DEF :a=(out Var.ToLower() /*c code*/ )
  ECHO result = %result:a%
```
`hello`

- Please give positive or negative feedback to this idea.

**Comment by darkbatcher** [comment]
Hi

`DEF` is already used for batch-based subroutines. As I understand it you would like to extend batch beeing able to use sort of inline C. Btw what you wrote is c++.

I know it possible to embed tinycc for exemple. But i don't see the advantage over `mod`

Maybe a module capable of jit-compiling c files would be a good idea though

**Comment by GroophyLifefor** [comment]
Hi 

frankly the reason I'm presenting such an idea is because people want to have full control of the terminal, and that's the way plugins are developing, and your project does just that, it would be nice to have a little more control.

Also I don't know c, I know `.ToLower()` from c#.

I never used `mod` and http://picobat.org/doc/mod, Even if I was read the document, I don't understand how do I use it and what its full function is?
