### ISSUE TITLE
Some pointer about parsing and executment

### ISSUE THREAD

**Issue by GroophyLifefor** [darkbatcher/picobat#4]
I intend to make some changes to the PicoBat project, but I have limited knowledge. Would it be possible for you to provide me with the `documentation of PicoBat`, or a document that explains `how the algorithm is handled` (in .pdf, .docx or other format)? Also, I'm not sure `what ESTR` stands for as I've seen it mentioned several times.

```mermaid
stateDiagram-v2
    direction LR
    [*] --> pBat_RunBatch
    pBat_RunBatch --> pBat_RunLine
    pBat_RunLine --> pBat_RunLine: !(pIn->bEof)
    pBat_RunLine --> pBat_ParseLine
    pBat_ParseLine --> pBat_RunParsedLine
    pBat_RunParsedLine --> RPL
    state RPL {
        direction LR
        pBat_SkipAllBlanks --> pBat_ExecOperators
        pBat_ExecOperators --> pBat_PopStreamStackUntilLock
        pBat_PopStreamStackUntilLock --> pBat_SetStreamStackLockState
        pBat_SetStreamStackLockState --> pBat_ExecOutput
        
    }
    RPL --> pBat_RunCommand
```

I did this in a short time without details, but this is the progress I was able to solve, it is difficult to find the right way because there is too much code.

**Comment by TSnake41** [comment]
ESTR stands for "Enhanced STRing" which is basically a strcuture containing a C string pointer along with the size of the allocated buffer.

It's pretty difficult to make a document summarizing how Picobat works due to the complexity of the project.

**Comment by GroophyLifefor** [comment]
```
console/pBat_Console.c:103:20: error: ‘FIONREAD’ undeclared (first use in this function); did you mean ‘FREAD’?
  103 |   ioctl(fileno(f), FIONREAD, &bytesWaiting);
      |                    ^~~~~~~~
      |                    FREAD
console/pBat_Console.c:103:20: note: each undeclared identifier is reported only once for each function it appears in
```

How can i solve this problem i am getting in msys2.
